### ISSUE TITLE
An error occurred when trying to create a controller of type 'BlogController'. Make sure that the controller has a parameterless public constructor.

### ISSUE THREAD

**Issue by bsubasic** [Shazwazza/Our.Umbraco.IoC#7]
From time to time I get this exception on calling API service from Angular (on the app start it works, but after some time it starts throwing this exception on some calls and right after exception it works fine again on another call - without reloading page, only via Ajax calls):

An error occurred when trying to create a controller of type 'BlogController'. Make sure that the controller has a parameterless public constructor.
---

```
An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = BlogController (ReflectionActivator), Services = [System.Web.Http.Controllers.IHttpController, umbraco.interfaces.IDiscoverable, Project.Web.ApiControllers.BlogController], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ApiDataProvider (ReflectionActivator), Services = [Project.Web.Business.DataAccess.Content.IApiDataProvider, Project.Web.Business.DataAccess.Content.ApiDataProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ContentTreeProvider (ReflectionActivator), Services = [Project.Web.Business.DataAccess.Content.ContentTreeProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = UmbracoHelper (DelegateActivator), Services = [Umbraco.Web.UmbracoHelper], Lifetime = Autofac.Core.Lifetime.MatchingScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> **Collection was modified after the enumerator was instantiated**. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.

at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Autofac.Core.Resolving.CircularDependencyDetector.CheckForCircularDependency(IComponentRegistration registration, Stack`1 activationStack, Int32 callDepth)
at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
at Our.Umbraco.IoC.UmbracoServices.<>c.<GetWebRegistrations>b__1_3(Resolver x)
at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)"
```

This is my custom configuration:

```
public class UmbracoStartup: ApplicationEventHandler
    {
        protected override void ApplicationInitialized(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            base.ApplicationInitialized(umbracoApplication, applicationContext);

            //If you are using Autofac:
            AutofacStartup.ContainerBuilding += (sender, args) =>
            {
                var myAppAssembly = typeof(BlogPageController).Assembly;

                //add our own services
                args.Builder.RegisterControllers(typeof(BlogPageController).Assembly);
                args.Builder.RegisterApiControllers(typeof(BlogController).Assembly);

                args.Builder.RegisterAssemblyTypes(myAppAssembly)
                    .AsImplementedInterfaces()
                    .AsSelf();
            };
        }
    }
```

This is my API controller:
```
    [CamelCaseFormatter]
    public class BlogController : UmbracoApiController
    {
        private readonly IApiDataProvider _apiDataProvider;

        public BlogController(IApiDataProvider apiDataProvider)
        {
            _apiDataProvider = apiDataProvider;
        }
```

```
    public class ApiDataProvider : IApiDataProvider
    {
        private readonly ContentTreeProvider _contentTreeProvider;

        public ApiDataProvider(ContentTreeProvider contentTreeProvider)
        {
            _contentTreeProvider = contentTreeProvider;
        }
```

```
    public class ContentTreeProvider
    {
        private readonly UmbracoHelper _umbracoHelper;

        public ContentTreeProvider(UmbracoHelper umbracoHelper)
        {
            _umbracoHelper = umbracoHelper;
        }
```

What can be the problem?

Thanks

#update 30.01.2019#

```
InnerException: {Message: "An error has occurred.",…}
ExceptionMessage: "Circular component dependency detected: Umbraco.Web.UmbracoContext."
ExceptionType: "Autofac.Core.DependencyResolutionException"
Message: "An error has occurred."
StackTrace: "   at Autofac.Core.Resolving.CircularDependencyDetector.CheckForCircularDependency(IComponentRegistration registration, Stack`1 activationStack, Int32 callDepth)
↵   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
↵   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
↵   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
↵   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
↵   at Our.Umbraco.IoC.UmbracoServices.<>c.<GetWebRegistrations>b__1_3(Resolver x)
↵   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
↵   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)"
```

**Comment by bsubasic** [comment]
Firstly, I tried to replace AssemblyScanning registration, I had before, with manual registrations but it didn't help.

```
       //args.Builder.RegisterAssemblyTypes(myAppAssembly)
       //.AsImplementedInterfaces()
       //.AsSelf()
```

When I replaced (overridden) registrations for `UmbracoContext` and `UmbracoHelper` I don't see these exceptions anymore (tested intensively for 1 hour)

```
args.Builder.Register(c => UmbracoContext.Current).AsSelf().InstancePerRequest() 
args.Builder.Register(c => new UmbracoHelper(UmbracoContext.Current)).InstancePerRequest();
```
I haven't figure out why this exception appeared before.

`ExceptionMessage: "Circular component dependency detected: Umbraco.Web.UmbracoContext."`
 
Can it be that `UmbracoContext `wasn't registered as `Lifetime.Request`?

**Comment by Shazwazza** [comment]
Hi sorry for the delay, been far too busy recently.

It doesn't look like you are registering your request based lifetime object `ContentTreeProvider` as request based? This requires UmbracoHelper which is request based. 

Here's the registration definitions: https://github.com/Shazwazza/Our.Umbraco.IoC/blob/master/src/Our.Umbraco.IoC/UmbracoServices.cs#L33

UmbracoContext isn't registered as request based, it's registered as Transient, that is because the factory resolves to Umbraco's own managed singleton - so it will end up being request based underneath anyways, the containers aren't creating this instance, just returning Umbraco's managed instance.

**Comment by Shazwazza** [comment]
We also don't want to tag UmbracoContext as request based since that will tell the containers that it needs to be disposed/managed by the container, but we don't want that since the instance is managed by Umbraco.

**Comment by Shazwazza** [comment]
Actually, just to be clear, the UmbracoContext (and most of the other services registered) are registered with the lifetime `ExternallyOwned` since that's what they are

**Comment by bsubasic** [comment]
Hi Shannon, 

Thanks for your detailed answer 👍

**Comment by Shazwazza** [comment]
Let me know if you still have issues, else please go ahead and close this ticket. Thanks!
